version: "3.7"
services:
  db:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgres/data/
    restart: unless-stopped
    environment:
      POSTGRES_DB: rmg-provider
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

volumes:
  postgres_data:
    driver: local
